[2025-06-06T05:00:50.763+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:00:49.677437+00:00 [queued]>
[2025-06-06T05:00:50.772+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:00:49.677437+00:00 [queued]>
[2025-06-06T05:00:50.773+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-06T05:00:50.786+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-06 05:00:49.677437+00:00
[2025-06-06T05:00:50.791+0000] {standard_task_runner.py:60} INFO - Started process 1338 to run task
[2025-06-06T05:00:50.794+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'LR_duration_prediction_training', 'train_model', 'manual__2025-06-06T05:00:49.677437+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/LR_duration-prediction_dag.py', '--cfg-path', '/tmp/tmp_bibyy4i']
[2025-06-06T05:00:50.795+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask train_model
[2025-06-06T05:00:50.806+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-06T05:00:50.836+0000] {task_command.py:423} INFO - Running <TaskInstance: LR_duration_prediction_training.train_model manual__2025-06-06T05:00:49.677437+00:00 [running]> on host a901f37d6140
[2025-06-06T05:00:50.893+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LR_duration_prediction_training' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T05:00:49.677437+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-06T05:00:49.677437+00:00'
[2025-06-06T05:00:51.147+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:00:51 INFO mlflow.tracking.fluent: Experiment with name 'nyc-taxi-experiment-LR' does not exist. Creating a new experiment.
[2025-06-06T05:01:11.612+0000] {logging_mixin.py:188} INFO - Loaded records: 3403766
[2025-06-06T05:01:18.099+0000] {logging_mixin.py:188} INFO - Records after preparation: 3316216
[2025-06-06T05:01:37.925+0000] {logging_mixin.py:188} INFO - Loaded records: 3288250
[2025-06-06T05:01:43.242+0000] {logging_mixin.py:188} INFO - Records after preparation: 3199715
[2025-06-06T05:01:59.379+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:01:59 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-06T05:02:03.374+0000] {logging_mixin.py:188} INFO - Model intercept: 23.85
[2025-06-06T05:02:04.770+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:02:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-06T05:02:04.799+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:02:04 INFO mlflow.tracking._tracking_service.client: üèÉ View run learned-dog-791 at: http://mlflow:5000/#/experiments/2/runs/348d79db999842778b15555252c4e757.
[2025-06-06T05:02:04.799+0000] {logging_mixin.py:188} WARNING - 2025/06/06 05:02:04 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/2.
[2025-06-06T05:02:04.810+0000] {logging_mixin.py:188} INFO - Model trained and logged with run_id: 348d79db999842778b15555252c4e757
[2025-06-06T05:02:05.032+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-06-06T05:02:05.041+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=LR_duration_prediction_training, task_id=train_model, execution_date=20250606T050049, start_date=20250606T050050, end_date=20250606T050205
[2025-06-06T05:02:05.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-06T05:02:05.135+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
